# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_host_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('art_city', models.CharField(max_length=200)),
                ('art_mail', models.CharField(max_length=200)),
                ('art_link', models.CharField(max_length=200)),
                ('art_category', models.CharField(max_length=200)),
                ('art_delete', models.BooleanField(default=False)),
                ('art_vote', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_id', models.CharField(max_length=200)),
                ('vote_is_it', models.BooleanField(default=False)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcgt.Gallery')),
            ],
        ),
    ]
