# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcgt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='art_add',
            field=models.ImageField(default='fcgt/media/no-img.jpg', upload_to='fcgt/media'),
        ),
    ]
