# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcgt', '0003_auto_20160428_1516'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='docfile',
            field=models.FileField(default='non_file.jpg', upload_to='documents/%Y/%m/%d'),
        ),
    ]
