# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcgt', '0004_auto_20160428_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='docfile',
            field=models.FileField(upload_to='arts'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
