# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcgt', '0005_auto_20160510_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='art_password',
            field=models.CharField(default=123, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gallery',
            name='art_category',
            field=models.CharField(choices=[('BlackAndWhite', '\u0427\u0435\u0440\u043d\u043e\u0435 \u0438 \u0431\u0435\u043b\u043e\u0435 \u0438 \u0441\u0435\u0440\u043e\u0435'), ('ProfiVsHobby', '\u0426\u0432\u0435\u0442\u043e\u043f\u0440\u043e\u0431\u044b'), ('Scatching', '\u0421\u043a\u0435\u0442\u0447\u0438\u043d\u0433'), ('CopyPast', 'Copy Paste'), ('MiniArt', '\u041c\u0438\u043d\u0438-\u0445\u0443\u0434\u043e\u0436\u043d\u0438\u043a\u0438')], max_length=200),
        ),
    ]
