# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcgt', '0007_auto_20160527_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('adress', models.CharField(max_length=200)),
                ('web', models.CharField(max_length=200)),
            ],
        ),
    ]
