# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcgt', '0009_auto_20170613_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='art_category',
            field=models.CharField(choices=[('monochrome_lab', '\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u0438\u044f Monochromos'), ('polychrome_planet', '\u041f\u043b\u0430\u043d\u0435\u0442\u0430 Polychromos'), ('pitt_artist', 'PITT Artist \u0441\u043a\u0435\u0442\u0447'), ('albrecht_durer', 'Albrecht durer: \u0440\u0430\u0431\u043e\u0442\u0430\u044e\u0442 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b\u044b'), ('connector', 'Connector: \u0441\u0430\u043c \u0441\u0435\u0431\u0435 \u043a\u043e\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440'), ('little_castle', '\u0417\u0430\u043c\u043e\u043a \u043c\u0430\u043b\u0435\u043d\u044c\u043a\u0438\u0445 \u0445\u0443\u0434\u043e\u0436\u043d\u0438\u043a\u043e\u0432')], max_length=200),
        ),
        migrations.AlterField(
            model_name='gallery2',
            name='art_category',
            field=models.CharField(choices=[('monochrome_lab', '\u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u0438\u044f Monochromos'), ('polychrome_planet', '\u041f\u043b\u0430\u043d\u0435\u0442\u0430 Polychromos'), ('pitt_artist', 'PITT Artist \u0441\u043a\u0435\u0442\u0447'), ('albrecht_durer', 'Albrecht durer: \u0440\u0430\u0431\u043e\u0442\u0430\u044e\u0442 \u043f\u0440\u043e\u0444\u0435\u0441\u0441\u0438\u043e\u043d\u0430\u043b\u044b'), ('connector', 'Connector: \u0441\u0430\u043c \u0441\u0435\u0431\u0435 \u043a\u043e\u043d\u0441\u0442\u0440\u0443\u043a\u0442\u043e\u0440'), ('little_castle', '\u0417\u0430\u043c\u043e\u043a \u043c\u0430\u043b\u0435\u043d\u044c\u043a\u0438\u0445 \u0445\u0443\u0434\u043e\u0436\u043d\u0438\u043a\u043e\u0432')], max_length=200),
        ),
    ]
