# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcgt', '0010_auto_20170613_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery2',
            name='small_image',
            field=models.FileField(default='', upload_to='arts'),
        ),
    ]
